routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::post('/post/store', 'PostController@store')->name('post.store');
Route::post('/post/destroy', 'PostController@destroy')->name('post.destroy');

Route::get('/like', 'LikeController@like')->name('like');

Route::post('/comment/store', 'CommentController@store')->name('comment.store');
Route::get('/comment/data', 'CommentController@data')->name('comment.data');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [
        'post_id','user_id','comment'
    ];
}

app/Like.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Like extends Model
{
    protected $fillable = [
        'post_id','user_id'
    ];
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'post','poto','user_id'
    ];

    public function getTotalLikesAttribute()
    {
        return $this->hasMany('App\Like')->where('post_id',$this->id)->count();

    }

    public function getTotalCommentsAttribute()
    {
        return $this->hasMany('App\Comment')->where('post_id',$this->id)->count();

    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Datatables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth',['except' => ['data']]);
    }

    public function store(Request $request)
    {

        $user = auth()->user();
        $post_id = $request->id_post;
        $comment = $request->comment;

        $data = new Comment;
        $data->post_id = $post_id;
        $data->user_id = $user->id;
        $data->comment = $comment;
        $data->save();

        Session::flash("flash_data", [
            "id_post"     => "$post_id",
            "type"      => "is_comment"
        ]);

        alert()->success('Berhasil Komentar !!', 'Sukses');
        return redirect()->back();
    }

    public function data(Request $request)
    {
        $id = $request->id;
        $data = DB::table('comments as a')
                ->where('post_id',$id)
                ->leftJoin('users as b','a.user_id','=','b.id')
                ->select('a.id','a.comment','a.post_id','b.name','a.updated_at')
                ->orderBy('a.updated_at', 'ASC');

        return Datatables::of($data)
        ->addColumn('commentSpan', function($data) {
            return view('span.item-comment',[
                'data' => $data,
            ]);
        })->make(true);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {

        $data = Post::query()->paginate(6);

        return view('home', compact('data'));
    }
}

app/Http/Controllers/LikeController.php
<?php

namespace App\Http\Controllers;

use App\Like;
use Illuminate\Http\Request;

class LikeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function like(Request $request)
    {

        $user = auth()->user();
        $post_id = $request->idpost;

        $checkLike = Like::query()->where('post_id',$post_id)->where('user_id',$user->id)->first();

        if(!empty($checkLike)) {
            $checkLike->delete();
            alert()->success('Unlike Berhasil', 'Sukses');
        }
        else {
            Like::create([
                'post_id' => $post_id,
                'user_id' => $user->id
            ]);

            alert()->success('Like Berhasil', 'Sukses');
        }
        return redirect()->back();
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Like;
use App\Post;
use Exception;
use App\Comment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Validator;
use Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth',['except' => ['index']]);
    }

    public function index(){

    }

    public function store(Request $request){

        $rules = [
            'post'   => 'required',
            'photo'  => 'required|mimes:jpeg,jpg,png|max:2028'
        ];

        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            $validator->getMessageBag()->add('is_post_status', 'Edit Form Is Not valid');
            alert()->error('Gagal Input !!', 'Error');
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $user = auth()->user();

        $data = new Post;
        $data->post = $request->post;
        $data->user_id = $user->id;

        try {

            $uploaded_cover = $request->file('photo');
            $extension = $uploaded_cover->getClientOriginalExtension();

            $filename = md5(time()) . '.' . $extension;

            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';
            $uploaded_cover->move($destinationPath, $filename);

            $data->poto = $filename;
            $data->save();
            alert()->success('Data Berhasil diupload !!', 'Sukses');

        } catch (\Exception $e) {
            alert()->error($e->getMessage(), 'Error');
        }


        return redirect()->back();
    }

    public function destroy(Request $request) {
        // return $request->all();

        $data = Post::find($request->id_post);

        if(!empty($data)) {
            $poto = $data->poto;


            Like::query()->where('post_id',$request->id_post)->delete();
            Comment::query()->where('post_id',$request->id_post)->delete();

            $data->delete();

            $filepath = public_path() . DIRECTORY_SEPARATOR . 'img'
                . DIRECTORY_SEPARATOR . $poto;

            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
            alert()->success('Data Berhasil dihapus!!', 'Sukses');
        } else {
            alert()->error('Gagal', 'Error');
        }

        return redirect()->back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<main role="main">
    <section class="jumbotron text-center bg-secondary mb-0">
        <div class="container">
            <h1 class="jumbotron-heading">Insta Web App </h1>
             <p class="lead">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
            <p>
                <a href="#" class="btn btn-primary my-2">Main call to action</a>
            </p>
        </div>
    </section>

    <div class="album bg-dark">
        <div class="container">
            <div class="row">
                @if (Auth::check())
                <div class="col-md-12">
                    <div class="card mt-3 mb-3">

                        <div class="card-header bg-secondary text-white">
                            <h5 class="card-title">New Status</h5>
                        </div>

                        <div class="card-body">
                            <form action="{{ route('post.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-md-5">
                                        <input type="text" name="post" class="form-control{{ $errors->has('issued_by') ? ' is-invalid' : '' }} mt-2" value="{{ old('post') }}" required placeholder="Write Status">
                                        @if ($errors->has('post'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('post') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="col-md-5">
                                        <div class="custom-file mt-2">
                                            <input type="file" class="custom-file-input" name="photo" required id="customFile">
                                            <label class="custom-file-label form-control mb-2 mr-sm-2" for="customFile">Choose file</label>
                                        </div>
                                    </div>
                                    <div class="col-md-2 mt-2">
                                        <button type="submit" class="btn btn-secondary mb-2">Submit</button>
                                    </div>
                                </div>
                        </form>
                        </div>
                    </div>

                </div>
                @endif
            </div>

            <div class="row mt-3">

                @foreach ($data as $item)

                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="{{ asset('img/'.$item->poto) }}" data-holder-rendered="true">
                        <div class="card-body">
                            <p class="card-text">{{ $item->post }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{{ route('like') }}?idpost={{$item->id}}">
                                        <button type="button" class="btn btn-sm btn-outline-primary"> {{ $item->total_likes }} Like</button>
                                    </a>
                                    <button type="button" class="btn btn-sm btn-outline-success"
                                        data-toggle="modal" data-target="#modal-comment" data-id="{{$item->id}}"> {{ $item->total_comments }} Comment</button>
                                    @if (Auth::check())
                                        @if ( Auth::user()->id == $item->user_id)
                                            <button type="button" class="btn btn-sm btn-outline-secondary"> Edit</button>
                                            <button type="button" class="btn btn-sm btn-outline-danger"
                                                data-toggle="modal" data-target="#modal-delete" data-id="{{$item->id}}">
                                                Hapus
                                            </button>
                                        @endif
                                    @endif

                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach




            </div>
            <div class="row">
                {{ $data->links() }}
            </div>


        </div>
    </div>
</main>

@include('modal.delete')
@include('modal.comment')

<footer class="bg-secondary text-white pb-3 pt-3">
    <div class="container">
      <p class="float-right">
            <a href="#">Back to top</a>
      </p>
      <p>Album example is © Bootstrap, but please download and customize it for yourself!</p>
      <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
{{-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> --}}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
<script type="text/javascript" src="{{ asset('asset-web/datatables/DataTables-1.10.21/js/jquery.dataTables.js') }}"></script>
<script type="text/javascript" src="{{ asset('asset-web/datatables/DataTables-1.10.21/js/dataTables.bootstrap4.js') }}"></script>
<script type="text/javascript" src="{{ asset('asset-web/datatables/FixedHeader-3.1.7/js/dataTables.fixedHeader.js') }}"></script>
<script type="text/javascript" src="{{ asset('asset-web/datatables/Responsive-2.2.4/js/dataTables.responsive.js') }}"></script>

<script>
    $(document).ready(function () {
        bsCustomFileInput.init()

        var commentTable = $('#table-comment').DataTable({
        pocessing: true,
        serverSide: true,
        searching: false,
        lengthChange: false,
        paging: false,
        ajax: {
            url: "{{ route('comment.data') }}",
            data: function (d) {
                d.id = $('#modal-comment').find('input[name=id]').val();
            }
        },
        columns: [

            {
                data: 'commentSpan',
                name: 'a.update_at',
                orderable: false,
            }

        ]
    })

        @if (session()->has('flash_data'))

            @if( session()->get('flash_data.type') == 'is_comment')
                var modal = $('#modal-comment')
                var id = "{{session()->get('flash_data.id_post')}}"

                modal.find('input[name=id]').val(id);
                modal.find('input[name=id_post]').val(id);

                modal.modal('show')

                commentTable.draw();
            @endif

        @endif

        $('#modal-delete').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var id     = button.data('id')

            var modal = $(this)

            modal.find('input[name=id_post]').val(id);
        })

        $('#modal-comment').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var modal = $(this)
            var id = button.data('id')

            modal.find('input[name=id]').val(id);
            modal.find('input[name=id_post]').val(id);

            commentTable.draw();

        });
    })
</script>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    {{-- <script src="{{ asset('js/app.js') }}" defer></script> --}}
    <script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">



    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{{ asset('asset-web/datatables/DataTables-1.10.21/css/dataTables.bootstrap4.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('asset-web/datatables/FixedHeader-3.1.7/css/fixedHeader.bootstrap4.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('asset-web/datatables/Responsive-2.2.4/css/responsive.bootstrap4.css') }}"/>
</head>
<body>
    @include('sweet::alert')
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main>
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/modal/comment.blade.php
<div class="modal fade" id="modal-comment">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-success">
                <h4 class="modal-title">List Comment</h4>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">

                <div class="row">
                    <div class="col-12">
                        <input type="hidden" name="id" value="" readonly />
                        <table id="table-comment" width="100%">
                            <thead>
                                <td width="100%"></td>
                            </thead>
                            <tbody >
                                <tr>
                                    <td>


                                    </td>
                                </tr>
                            </tbody>
                        </table>

                    </div>

                    <div class="col-12">
                        <div class="card mt-4 mr-4 ml-4 mb-3">
                            <form role="form" action="{{ route('comment.store') }}" method="POST">
                                @csrf
                                <input type="hidden" name="id_post" value="" readonly />
                                <div class="card-body">

                                    <div class="form-group">
                                        <textarea class="form-control" name="comment" rows="2" placeholder="Write your comment"></textarea>
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>

                                </div>
                            </form>
                        </div>

                    </div>
                </div>

            </div>

        </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/modal/delete.blade.php
<div class="modal fade" id="modal-delete">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-danger">
                <h4 class="modal-title">Konfirmasi Hapus Status</h4>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('post.destroy') }}" method="POST">
                @csrf
                <div class="modal-body">
                    <div class="row d-flex justify-content-center">
                        <h4 class="lead">Yakin ingin menghapus status ?</h4>
                        <input type="hidden" name="id_post" value="{{ old('id_request') }}" readonly>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn bg-danger">Konfirmasi Hapus</button>
                </div>
            </form>

        </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/span/item-comment.blade.php
<div class="card">
    <div class="card-header">
        <h2>{{ $data->name }}</h2>
    </div>
    <div class="card-body">
        <blockquote class="blockquote mb-0">
            {{ $data->comment }}
            <footer class="blockquote-footer">{{ date("H:i d M Y", strtotime($data->updated_at)) }}</footer>
        </blockquote>
    </div>
</div>